[[upgrade-standard]]
=== 标准升级

标准升级是升级 Kibana 最直接的方法，仅支持 4.2 及以上的版本。

如果你之前没有升级过 Kibana，参考 <<upgrade,table>> 来验证你的版本是否支持标准升级。

NOTE: 如果你从 Kibana 中保存或导出过依赖 <<search,Elasticsearch Query DSL>> 的对象，
确保参考过 Elasticsearch {es-ref}breaking-changes.html[breaking changes]
文档并且按照其指引进行过必要的修复。

[float]
==== 用 `deb` 或 `rpm` 包进行升级
. 在当前系统中使用合适的命令停止当前运行的 Kibana 进程。
. 使用 `rpm` 或 `dpkg` 安装新的包。所有的文件应该被放置到合适的位置并且配置文件不应该被覆盖。
+
[NOTE]
--
Kibana 4.x 的配置文件地址不同于 5.0+，所以如果你是从 4.x 升级的，
你需要把配置从原有的配置文件(`/opt/kibana/config/kibana.yml`)拷贝到新的配置文件(`/etc/kibana/kibana.yml`)。

确保你移动或者升级了 <<breaking-changes,breaking changes>> 文件中指明的配置项，
否则 Kibana 将无法启动。
--
. 运用以下方法升级插件：删除已存在的插件，使用 `kibana-plugin` 脚本重新安装合适的版本。
  参考 <<kibana-plugins,plugins>> 文档获取更多信息。
. 在当前系统中使用合适的命令开启新的 Kibana 进程。

[float]
==== 用 `zip` 或 `tar.gz` 压缩包进行升级

. 将 `zip` 或 `tar.gz` 压缩包解压到一个新的文件夹，确保 `config` 文件夹或 `data` 文件夹没有被覆盖。
. 将原安装中 `config` 文件夹下的所有文件拷贝到新安装中。确保你移动或者升级了 <<breaking-changes,breaking changes>>
  文件中指明的配置项，否则 Kibana 将无法启动。
. 将原安装中的 `data` 文件夹下的所有文件拷贝到新安装中。
. 使用 `kibana-plugin` 脚本重新安装合适的版本。参考 <<kibana-plugins,plugins>> 文档获取更多信息。
. 关闭原 Kibana 进程。
. 开启新 Kibana 进程。

